[tool.poetry]
name = "im"
version = "0.1.0"
description = ""
authors = ""

[tool.poetry.dependencies]
pandas = "*"
psycopg2-binary = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
