#
# Basic setup to run as user and GitHub action.
#
version: '3'

services:
  base_app:
    cap_add:
      - SYS_ADMIN
    environment:
      - AM_ECR_BASE_PATH=$AM_ECR_BASE_PATH
      - AM_PUBLISH_NOTEBOOK_AWS_PROFILE=$AM_PUBLISH_NOTEBOOK_AWS_PROFILE
      - AM_PUBLISH_NOTEBOOK_S3_PATH=$AM_PUBLISH_NOTEBOOK_S3_PATH
      - AM_S3_BUCKET=$AM_S3_BUCKET
      - AM_TELEGRAM_TOKEN=$AM_TELEGRAM_TOKEN
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - GH_ACTION_ACCESS_TOKEN=$GH_ACTION_ACCESS_TOKEN
      # This env var is used by GH Action to signal that we are inside the CI.
      - CI=$CI
    image: ${IMAGE}
    # TODO(gp): I think this is needed only when mounting fstab.
    #privileged: true
    restart: "no"
    volumes:
      - ~/.aws:/root/.aws
      - ~/.config/gspread_pandas/:/root/.config/gspread_pandas/
      - ~/.config/gh:/root/.config/gh
      # No need to mount file systems.
      #- ../docker_build/fstab:/etc/fstab

  # Mount `amp` when it is used as supermodule.
  app:
    extends:
      base_app
    volumes:
      - ../../:/app

  jupyter_server:
    command: devops/docker_scripts/run_jupyter_server.sh
    environment:
      - PORT=${PORT}
    extends:
      app
    ports:
      # TODO(gp): Rename `AM_PORT`.
      - "${PORT}:${PORT}"

  # TODO(gp): For some reason the following doesn't work.
  #  jupyter_server_test:
  #    command: jupyter notebook -h 2>&1 >/dev/null
  #    extends:
  #      jupyter_server

  jupyter_server_test:
    command: jupyter notebook -h 2>&1 >/dev/null
    environment:
      - PORT=${PORT}
    extends:
      app
    ports:
      - "${PORT}:${PORT}"
