#
# Basic setup to run as user and GitHub action.
#
version: '3'

services:
  base_app:
    cap_add:
      - SYS_ADMIN
    environment:
      - AM_AWS_PROFILE=$AM_AWS_PROFILE
      - AM_ECR_BASE_PATH=$AM_ECR_BASE_PATH
      - AM_PUBLISH_NOTEBOOK_LOCAL_PATH=$AM_PUBLISH_NOTEBOOK_LOCAL_PATH
      - AM_S3_BUCKET=$AM_S3_BUCKET
      - AM_TG_BUILDBOT_TOKEN=$AM_TG_BUILDBOT_TOKEN
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - GH_ACTION_ACCESS_TOKEN=$GH_ACTION_ACCESS_TOKEN
      # This env var is used by GH Action to signal that we are inside the CI.
      - CI=$CI
    image: ${IMAGE}
    # This is needed for dind (Docker-in-docker). It is also needed if one
    # wants to mount fstabs.
    privileged: true
    restart: "no"
    volumes:
      # TODO(gp): We should pass the value of $HOME from dev.Dockerfile to here.
      # E.g., we might define $HOME in the env file.
      - ~/.aws:/home/.aws
      - ~/.config/gspread_pandas/:/home/.config/gspread_pandas/
      - ~/.config/gh:/home/.config/gh
      # No need to mount file systems.
      #- ../docker_build/fstab:/etc/fstab

  # Mount `amp` when it is used as supermodule.
  app:
    extends:
      base_app
    volumes:
      - ../../:/app

  jupyter_server:
    command: devops/docker_run/run_jupyter_server.sh
    environment:
      - PORT=${PORT}
    extends:
      app
    ports:
      # TODO(gp): Rename `AM_PORT`.
      - "${PORT}:${PORT}"

  # TODO(gp): For some reason the following doesn't work.
  #  jupyter_server_test:
  #    command: jupyter notebook -h 2>&1 >/dev/null
  #    extends:
  #      jupyter_server

  jupyter_server_test:
    command: jupyter notebook -h 2>&1 >/dev/null
    environment:
      - PORT=${PORT}
    extends:
      app
    ports:
      - "${PORT}:${PORT}"
