- name: Install openvpn server
  hosts: 13.51.59.43
  become: true
  gather_facts: true
  roles:
    - { role: roles/vpn_configure_server }

# ansible-playbook plays/vpn_configure_server.yml --user ubuntu --private-key=/root/.ssh/id_rsa_crypto --inventory 13.51.59.43, --ask-vault-pass