version: '3.8'

services:
  blog:
    container_name: blog
    build: .
    image: blog
    ports:
      - "5001:5001"
    networks:
      - blognet
    depends_on:
      - rethinkdb

  rethinkdb:
    container_name: rethinkdb
    image: rethinkdb
    networks:
      - blognet
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"

networks:
  blognet:
