---
vpn_region: eu
easyrsa_dir: /usr/share/easy-rsa/
easyrsa_dn_mode_cn_only: false

easyrsa_pki_dir: /opt/pki
easyrsa_pki_ca_key: "{{ easyrsa_pki_dir }}/private/ca.key"
easyrsa_pki_ca_cert: "{{ easyrsa_pki_dir }}/ca.crt"
easyrsa_pki_crl: "{{ easyrsa_pki_dir }}/crl.pem"
easyrsa_pki_path_certs: "{{ easyrsa_pki_dir }}/issued"
easyrsa_pki_path_keys: "{{ easyrsa_pki_dir }}/private"
easyrsa_pki_server_cert: "{{ easyrsa_pki_path_certs }}/server@{{ openvpn_server_common_name }}.crt"
easyrsa_pki_server_key: "{{ easyrsa_pki_path_keys }}/server@{{ openvpn_server_common_name }}.key"

easyrsa_algo: ec
easyrsa_curve: secp384r1
easyrsa_key_size: 2048 #Only used when easyrsa_algo: rsa
easyrsa_digest: sha256
easyrsa_ca_expiration: 3650
easyrsa_cert_expiration: 3650
easyrsa_crl_days: 180

openvpn_dh: none
openvpn_ecdh_curve: prime256v1
openvpn_data_ciphers: "AES-128-GCM"
openvpn_data_ciphers_fallback: "AES-128-GCM"
openvpn_auth_digest: "SHA256"
openvpn_tls_cipher: "TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256"

openvpn_path: "/etc/openvpn"
openvpn_path_ccd: "{{ openvpn_path }}/ccd" 
openvpn_ta_key: "{{ openvpn_path }}/ta-{{ openvpn_server_port }}.key"

gauth_username: gauth
gauth_group: gauth
gauth_dir: /etc/openvpn/google-authenticator
gauth_pam_file: /etc/pam.d/openvpn
gauth_openvpn_plugin: /usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-auth-pam.so
gauth_openvpn_pam_module: /usr/lib/x86_64-linux-gnu/security/pam_google_authenticator.so