version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'

  worker:
    build: worker
    volumes:
      - ./worker:/app
    environment:
      - PYTHONUNBUFFERED=1

  server:
    build: server
    volumes:
      - ./server:/app
    ports:
      - '5001:5001'
