name: Build image
on:
  workflow_dispatch:

jobs:

  Build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Cleanup
        run: sudo chmod 777 -R .

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          # TODO(gp): Not needed?
          #ssh-key: ${{ secrets.GH_ACTION_SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/gh_requirements.txt

      - name: Run 'docker_release_dev_image' workflow
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          GH_ACTION_ACCESS_TOKEN: ${{ secrets.GH_ACTION_ACCESS_TOKEN }}
          AM_ECR_BASE_PATH: ${{ secrets.AM_ECR_BASE_PATH }}
          AM_S3_BUCKET: ${{ secrets.AM_S3_BUCKET }}
          AM_TELEGRAM_TOKEN: ${{ secrets.AM_TELEGRAM_TOKEN }}
        run: invoke docker_release_dev_image

      - name: Send Telegram notification for success
        if: ${{ success() }}
        #if: ${{ success() && github.ref == 'refs/heads/master' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.AM_TG_BUILDBOT_CHATID }}
          token: ${{ secrets.AM_TG_BUILDBOT_TOKEN }}
          message: |
            ðŸŽ‰ A new Docker image `amp` was successfully built. Please pull the new image.
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Send Telegram notification for failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.AM_TG_BUILDBOT_CHATID }}
          token: ${{ secrets.AM_TG_BUILDBOT_TOKEN }}
          message: |
            ðŸ§¨ IMAGE BUILD PROCESS FAILED
            Build failure '${{ github.workflow }}'
            Repo: '${{ github.repository }}'
            Branch: '$${{ github.head_ref }}'
            Event: '${{ github.event_name }}'
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
