name: Run linter
on:
  push:
    branches-ignore:
      - "master"
  workflow_dispatch:

jobs:
  Run_linter_mark_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Post status if was triggered manually
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "Run_linter"
          description: 'Added to queue, waiting for free runner (manual run)'
          state: pending
          sha: ${{ github.sha }}
          target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  Run_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Post status if was triggered manually
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "Run_linter"
          description: 'Job in progress (manual run)'
          state: pending
          sha: ${{ github.sha }}
          target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GH_ACTION_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GH_ACTION_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Cleanup
        run: sudo chmod 777 -R .

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          ssh-key: ${{ secrets.GH_ACTION_SSH_PRIVATE_KEY }}
          fetch-depth: 0
          ref: master

      - name: Switch branch
        run: |
          git checkout origin/${GITHUB_REF##*/}

      - name: Pull image
        run: make docker_pull

      - name: Run linter for the branch
        run: make lint_branch

      - name: Post status if was triggered manually
        if: ${{ always() && github.event_name == 'workflow_dispatch' }}
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "Run_linter"
          description: 'Job is done (manual run)'
          state: ${{ job.status }}
          sha: ${{ github.sha }}
          target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
